apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsl-app-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fsl-app
  template:
    metadata:
      labels:
        app: fsl-app
    spec:
      containers:
      - name: fsl-app-container
        image: 627129177687.dkr.ecr.us-east-1.amazonaws.com/raja-fsl-app:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: my-secret

